// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/api/dedupe_engine.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Initial message from stream handler to start a backup session
type BackupStart struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientId        string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                        // Identifier for the logical client/source
	BackupJobId     string                 `protobuf:"bytes,2,opt,name=backup_job_id,json=backupJobId,proto3" json:"backup_job_id,omitempty"`             // Unique ID for this backup job
	BackupPolicyId  string                 `protobuf:"bytes,3,opt,name=backup_policy_id,json=backupPolicyId,proto3" json:"backup_policy_id,omitempty"`    // ID of the policy governing this backup
	EncryptionKeyId string                 `protobuf:"bytes,4,opt,name=encryption_key_id,json=encryptionKeyId,proto3" json:"encryption_key_id,omitempty"` // Reference to encryption key used (if any)
	Timestamp       int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                     // Unix timestamp of backup start
	SourceType      string                 `protobuf:"bytes,6,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`                  // e.g., "filesystem", "database", "vm", "cloud_storage"
	SourceDetails   string                 `protobuf:"bytes,7,opt,name=source_details,json=sourceDetails,proto3" json:"source_details,omitempty"`         // JSON or specific format for source-specific config
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BackupStart) Reset() {
	*x = BackupStart{}
	mi := &file_pkg_api_dedupe_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupStart) ProtoMessage() {}

func (x *BackupStart) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_dedupe_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupStart.ProtoReflect.Descriptor instead.
func (*BackupStart) Descriptor() ([]byte, []int) {
	return file_pkg_api_dedupe_engine_proto_rawDescGZIP(), []int{0}
}

func (x *BackupStart) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *BackupStart) GetBackupJobId() string {
	if x != nil {
		return x.BackupJobId
	}
	return ""
}

func (x *BackupStart) GetBackupPolicyId() string {
	if x != nil {
		return x.BackupPolicyId
	}
	return ""
}

func (x *BackupStart) GetEncryptionKeyId() string {
	if x != nil {
		return x.EncryptionKeyId
	}
	return ""
}

func (x *BackupStart) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BackupStart) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *BackupStart) GetSourceDetails() string {
	if x != nil {
		return x.SourceDetails
	}
	return ""
}

// Message for sending file/data object metadata and data segments
type FileSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`                   // Original full path of the file/object identifier
	FileSize      uint64                 `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`                  // Total size of the file/object
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                                           // Raw data segment of the file/object
	Offset        uint64                 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`                                      // Offset of this segment within the file/object
	IsLastSegment bool                   `protobuf:"varint,5,opt,name=is_last_segment,json=isLastSegment,proto3" json:"is_last_segment,omitempty"` // True if this is the last segment for the file/object
	FileHash      string                 `protobuf:"bytes,6,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`                   // Optional: Hash of the entire file/object (e.g., Blake3)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSegment) Reset() {
	*x = FileSegment{}
	mi := &file_pkg_api_dedupe_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSegment) ProtoMessage() {}

func (x *FileSegment) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_dedupe_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSegment.ProtoReflect.Descriptor instead.
func (*FileSegment) Descriptor() ([]byte, []int) {
	return file_pkg_api_dedupe_engine_proto_rawDescGZIP(), []int{1}
}

func (x *FileSegment) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileSegment) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FileSegment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileSegment) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileSegment) GetIsLastSegment() bool {
	if x != nil {
		return x.IsLastSegment
	}
	return false
}

func (x *FileSegment) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

// Stream Handler sends a stream of these messages
type BackupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RequestType:
	//
	//	*BackupRequest_StartBackup
	//	*BackupRequest_FileSegment
	//	*BackupRequest_EndBackup
	RequestType   isBackupRequest_RequestType `protobuf_oneof:"request_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupRequest) Reset() {
	*x = BackupRequest{}
	mi := &file_pkg_api_dedupe_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRequest) ProtoMessage() {}

func (x *BackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_dedupe_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRequest.ProtoReflect.Descriptor instead.
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_dedupe_engine_proto_rawDescGZIP(), []int{2}
}

func (x *BackupRequest) GetRequestType() isBackupRequest_RequestType {
	if x != nil {
		return x.RequestType
	}
	return nil
}

func (x *BackupRequest) GetStartBackup() *BackupStart {
	if x != nil {
		if x, ok := x.RequestType.(*BackupRequest_StartBackup); ok {
			return x.StartBackup
		}
	}
	return nil
}

func (x *BackupRequest) GetFileSegment() *FileSegment {
	if x != nil {
		if x, ok := x.RequestType.(*BackupRequest_FileSegment); ok {
			return x.FileSegment
		}
	}
	return nil
}

func (x *BackupRequest) GetEndBackup() *BackupEnd {
	if x != nil {
		if x, ok := x.RequestType.(*BackupRequest_EndBackup); ok {
			return x.EndBackup
		}
	}
	return nil
}

type isBackupRequest_RequestType interface {
	isBackupRequest_RequestType()
}

type BackupRequest_StartBackup struct {
	StartBackup *BackupStart `protobuf:"bytes,1,opt,name=start_backup,json=startBackup,proto3,oneof"`
}

type BackupRequest_FileSegment struct {
	FileSegment *FileSegment `protobuf:"bytes,2,opt,name=file_segment,json=fileSegment,proto3,oneof"`
}

type BackupRequest_EndBackup struct {
	EndBackup *BackupEnd `protobuf:"bytes,3,opt,name=end_backup,json=endBackup,proto3,oneof"`
}

func (*BackupRequest_StartBackup) isBackupRequest_RequestType() {}

func (*BackupRequest_FileSegment) isBackupRequest_RequestType() {}

func (*BackupRequest_EndBackup) isBackupRequest_RequestType() {}

// Message from stream handler to signal end of backup session
type BackupEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupJobId   string                 `protobuf:"bytes,1,opt,name=backup_job_id,json=backupJobId,proto3" json:"backup_job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`   // e.g., "COMPLETED", "FAILED"
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"` // Optional: summary message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupEnd) Reset() {
	*x = BackupEnd{}
	mi := &file_pkg_api_dedupe_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupEnd) ProtoMessage() {}

func (x *BackupEnd) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_dedupe_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupEnd.ProtoReflect.Descriptor instead.
func (*BackupEnd) Descriptor() ([]byte, []int) {
	return file_pkg_api_dedupe_engine_proto_rawDescGZIP(), []int{3}
}

func (x *BackupEnd) GetBackupJobId() string {
	if x != nil {
		return x.BackupJobId
	}
	return ""
}

func (x *BackupEnd) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BackupEnd) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

// Server sends a stream of these messages back to the stream handler
type BackupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ResponseType:
	//
	//	*BackupResponse_StatusUpdate
	//	*BackupResponse_ErrorMessage
	ResponseType  isBackupResponse_ResponseType `protobuf_oneof:"response_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupResponse) Reset() {
	*x = BackupResponse{}
	mi := &file_pkg_api_dedupe_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupResponse) ProtoMessage() {}

func (x *BackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_dedupe_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupResponse.ProtoReflect.Descriptor instead.
func (*BackupResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_dedupe_engine_proto_rawDescGZIP(), []int{4}
}

func (x *BackupResponse) GetResponseType() isBackupResponse_ResponseType {
	if x != nil {
		return x.ResponseType
	}
	return nil
}

func (x *BackupResponse) GetStatusUpdate() *BackupStatus {
	if x != nil {
		if x, ok := x.ResponseType.(*BackupResponse_StatusUpdate); ok {
			return x.StatusUpdate
		}
	}
	return nil
}

func (x *BackupResponse) GetErrorMessage() *BackupError {
	if x != nil {
		if x, ok := x.ResponseType.(*BackupResponse_ErrorMessage); ok {
			return x.ErrorMessage
		}
	}
	return nil
}

type isBackupResponse_ResponseType interface {
	isBackupResponse_ResponseType()
}

type BackupResponse_StatusUpdate struct {
	StatusUpdate *BackupStatus `protobuf:"bytes,1,opt,name=status_update,json=statusUpdate,proto3,oneof"`
}

type BackupResponse_ErrorMessage struct {
	ErrorMessage *BackupError `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3,oneof"`
}

func (*BackupResponse_StatusUpdate) isBackupResponse_ResponseType() {}

func (*BackupResponse_ErrorMessage) isBackupResponse_ResponseType() {}

// Status update from server to stream handler during backup
type BackupStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BackupJobId       string                 `protobuf:"bytes,1,opt,name=backup_job_id,json=backupJobId,proto3" json:"backup_job_id,omitempty"`
	CurrentFile       string                 `protobuf:"bytes,2,opt,name=current_file,json=currentFile,proto3" json:"current_file,omitempty"`
	BytesProcessed    uint64                 `protobuf:"varint,3,opt,name=bytes_processed,json=bytesProcessed,proto3" json:"bytes_processed,omitempty"`
	BytesDeduplicated uint64                 `protobuf:"varint,4,opt,name=bytes_deduplicated,json=bytesDeduplicated,proto3" json:"bytes_deduplicated,omitempty"`
	Message           string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BackupStatus) Reset() {
	*x = BackupStatus{}
	mi := &file_pkg_api_dedupe_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupStatus) ProtoMessage() {}

func (x *BackupStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_dedupe_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupStatus.ProtoReflect.Descriptor instead.
func (*BackupStatus) Descriptor() ([]byte, []int) {
	return file_pkg_api_dedupe_engine_proto_rawDescGZIP(), []int{5}
}

func (x *BackupStatus) GetBackupJobId() string {
	if x != nil {
		return x.BackupJobId
	}
	return ""
}

func (x *BackupStatus) GetCurrentFile() string {
	if x != nil {
		return x.CurrentFile
	}
	return ""
}

func (x *BackupStatus) GetBytesProcessed() uint64 {
	if x != nil {
		return x.BytesProcessed
	}
	return 0
}

func (x *BackupStatus) GetBytesDeduplicated() uint64 {
	if x != nil {
		return x.BytesDeduplicated
	}
	return 0
}

func (x *BackupStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Error message from server to stream handler
type BackupError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupJobId   string                 `protobuf:"bytes,1,opt,name=backup_job_id,json=backupJobId,proto3" json:"backup_job_id,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupError) Reset() {
	*x = BackupError{}
	mi := &file_pkg_api_dedupe_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupError) ProtoMessage() {}

func (x *BackupError) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_dedupe_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupError.ProtoReflect.Descriptor instead.
func (*BackupError) Descriptor() ([]byte, []int) {
	return file_pkg_api_dedupe_engine_proto_rawDescGZIP(), []int{6}
}

func (x *BackupError) GetBackupJobId() string {
	if x != nil {
		return x.BackupJobId
	}
	return ""
}

func (x *BackupError) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *BackupError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RestoreRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ClientId               string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	BackupJobId            string                 `protobuf:"bytes,2,opt,name=backup_job_id,json=backupJobId,proto3" json:"backup_job_id,omitempty"`                                  // The backup job to restore from
	FilesToRestore         []string               `protobuf:"bytes,3,rep,name=files_to_restore,json=filesToRestore,proto3" json:"files_to_restore,omitempty"`                         // List of specific files/paths to restore
	RestoreDestinationPath string                 `protobuf:"bytes,4,opt,name=restore_destination_path,json=restoreDestinationPath,proto3" json:"restore_destination_path,omitempty"` // Path on client/source to restore to
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_pkg_api_dedupe_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_dedupe_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_dedupe_engine_proto_rawDescGZIP(), []int{7}
}

func (x *RestoreRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RestoreRequest) GetBackupJobId() string {
	if x != nil {
		return x.BackupJobId
	}
	return ""
}

func (x *RestoreRequest) GetFilesToRestore() []string {
	if x != nil {
		return x.FilesToRestore
	}
	return nil
}

func (x *RestoreRequest) GetRestoreDestinationPath() string {
	if x != nil {
		return x.RestoreDestinationPath
	}
	return ""
}

type RestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestoreJobId  string                 `protobuf:"bytes,1,opt,name=restore_job_id,json=restoreJobId,proto3" json:"restore_job_id,omitempty"` // Unique ID for the restore operation
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                   // e.g., "INITIATED", "FAILED"
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_pkg_api_dedupe_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_dedupe_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_dedupe_engine_proto_rawDescGZIP(), []int{8}
}

func (x *RestoreResponse) GetRestoreJobId() string {
	if x != nil {
		return x.RestoreJobId
	}
	return ""
}

func (x *RestoreResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RestoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RestoreDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestoreJobId  string                 `protobuf:"bytes,1,opt,name=restore_job_id,json=restoreJobId,proto3" json:"restore_job_id,omitempty"` // No specific data needed from stream handler during stream, it's mostly for flow control
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreDataRequest) Reset() {
	*x = RestoreDataRequest{}
	mi := &file_pkg_api_dedupe_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreDataRequest) ProtoMessage() {}

func (x *RestoreDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_dedupe_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreDataRequest.ProtoReflect.Descriptor instead.
func (*RestoreDataRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_dedupe_engine_proto_rawDescGZIP(), []int{9}
}

func (x *RestoreDataRequest) GetRestoreJobId() string {
	if x != nil {
		return x.RestoreJobId
	}
	return ""
}

type RestoreDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestoreJobId  string                 `protobuf:"bytes,1,opt,name=restore_job_id,json=restoreJobId,proto3" json:"restore_job_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`                   // Original full path of the file/object
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                                           // Raw data segment of the file/object
	Offset        uint64                 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`                                      // Offset of this segment within the file/object
	IsLastSegment bool                   `protobuf:"varint,5,opt,name=is_last_segment,json=isLastSegment,proto3" json:"is_last_segment,omitempty"` // True if this is the last segment for the file/object
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreDataResponse) Reset() {
	*x = RestoreDataResponse{}
	mi := &file_pkg_api_dedupe_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreDataResponse) ProtoMessage() {}

func (x *RestoreDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_dedupe_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreDataResponse.ProtoReflect.Descriptor instead.
func (*RestoreDataResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_dedupe_engine_proto_rawDescGZIP(), []int{10}
}

func (x *RestoreDataResponse) GetRestoreJobId() string {
	if x != nil {
		return x.RestoreJobId
	}
	return ""
}

func (x *RestoreDataResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *RestoreDataResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RestoreDataResponse) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *RestoreDataResponse) GetIsLastSegment() bool {
	if x != nil {
		return x.IsLastSegment
	}
	return false
}

var File_pkg_api_dedupe_engine_proto protoreflect.FileDescriptor

const file_pkg_api_dedupe_engine_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/api/dedupe_engine.proto\x12\rdedupe_engine\"\x8a\x02\n" +
	"\vBackupStart\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\"\n" +
	"\rbackup_job_id\x18\x02 \x01(\tR\vbackupJobId\x12(\n" +
	"\x10backup_policy_id\x18\x03 \x01(\tR\x0ebackupPolicyId\x12*\n" +
	"\x11encryption_key_id\x18\x04 \x01(\tR\x0fencryptionKeyId\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vsource_type\x18\x06 \x01(\tR\n" +
	"sourceType\x12%\n" +
	"\x0esource_details\x18\a \x01(\tR\rsourceDetails\"\xb8\x01\n" +
	"\vFileSegment\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x04R\bfileSize\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x04R\x06offset\x12&\n" +
	"\x0fis_last_segment\x18\x05 \x01(\bR\risLastSegment\x12\x1b\n" +
	"\tfile_hash\x18\x06 \x01(\tR\bfileHash\"\xdc\x01\n" +
	"\rBackupRequest\x12?\n" +
	"\fstart_backup\x18\x01 \x01(\v2\x1a.dedupe_engine.BackupStartH\x00R\vstartBackup\x12?\n" +
	"\ffile_segment\x18\x02 \x01(\v2\x1a.dedupe_engine.FileSegmentH\x00R\vfileSegment\x129\n" +
	"\n" +
	"end_backup\x18\x03 \x01(\v2\x18.dedupe_engine.BackupEndH\x00R\tendBackupB\x0e\n" +
	"\frequest_type\"a\n" +
	"\tBackupEnd\x12\"\n" +
	"\rbackup_job_id\x18\x01 \x01(\tR\vbackupJobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\"\xa8\x01\n" +
	"\x0eBackupResponse\x12B\n" +
	"\rstatus_update\x18\x01 \x01(\v2\x1b.dedupe_engine.BackupStatusH\x00R\fstatusUpdate\x12A\n" +
	"\rerror_message\x18\x02 \x01(\v2\x1a.dedupe_engine.BackupErrorH\x00R\ferrorMessageB\x0f\n" +
	"\rresponse_type\"\xc7\x01\n" +
	"\fBackupStatus\x12\"\n" +
	"\rbackup_job_id\x18\x01 \x01(\tR\vbackupJobId\x12!\n" +
	"\fcurrent_file\x18\x02 \x01(\tR\vcurrentFile\x12'\n" +
	"\x0fbytes_processed\x18\x03 \x01(\x04R\x0ebytesProcessed\x12-\n" +
	"\x12bytes_deduplicated\x18\x04 \x01(\x04R\x11bytesDeduplicated\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"u\n" +
	"\vBackupError\x12\"\n" +
	"\rbackup_job_id\x18\x01 \x01(\tR\vbackupJobId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xb5\x01\n" +
	"\x0eRestoreRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\"\n" +
	"\rbackup_job_id\x18\x02 \x01(\tR\vbackupJobId\x12(\n" +
	"\x10files_to_restore\x18\x03 \x03(\tR\x0efilesToRestore\x128\n" +
	"\x18restore_destination_path\x18\x04 \x01(\tR\x16restoreDestinationPath\"i\n" +
	"\x0fRestoreResponse\x12$\n" +
	"\x0erestore_job_id\x18\x01 \x01(\tR\frestoreJobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\":\n" +
	"\x12RestoreDataRequest\x12$\n" +
	"\x0erestore_job_id\x18\x01 \x01(\tR\frestoreJobId\"\xac\x01\n" +
	"\x13RestoreDataResponse\x12$\n" +
	"\x0erestore_job_id\x18\x01 \x01(\tR\frestoreJobId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x04R\x06offset\x12&\n" +
	"\x0fis_last_segment\x18\x05 \x01(\bR\risLastSegment2\x92\x02\n" +
	"\rBackupService\x12O\n" +
	"\fStreamBackup\x12\x1c.dedupe_engine.BackupRequest\x1a\x1d.dedupe_engine.BackupResponse(\x010\x01\x12P\n" +
	"\x0fInitiateRestore\x12\x1d.dedupe_engine.RestoreRequest\x1a\x1e.dedupe_engine.RestoreResponse\x12^\n" +
	"\x11StreamRestoreData\x12!.dedupe_engine.RestoreDataRequest\x1a\".dedupe_engine.RestoreDataResponse(\x010\x01B7Z5github.com/radhakrishnan.venkat/dedupe-engine/pkg/apib\x06proto3"

var (
	file_pkg_api_dedupe_engine_proto_rawDescOnce sync.Once
	file_pkg_api_dedupe_engine_proto_rawDescData []byte
)

func file_pkg_api_dedupe_engine_proto_rawDescGZIP() []byte {
	file_pkg_api_dedupe_engine_proto_rawDescOnce.Do(func() {
		file_pkg_api_dedupe_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_dedupe_engine_proto_rawDesc), len(file_pkg_api_dedupe_engine_proto_rawDesc)))
	})
	return file_pkg_api_dedupe_engine_proto_rawDescData
}

var file_pkg_api_dedupe_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_api_dedupe_engine_proto_goTypes = []any{
	(*BackupStart)(nil),         // 0: dedupe_engine.BackupStart
	(*FileSegment)(nil),         // 1: dedupe_engine.FileSegment
	(*BackupRequest)(nil),       // 2: dedupe_engine.BackupRequest
	(*BackupEnd)(nil),           // 3: dedupe_engine.BackupEnd
	(*BackupResponse)(nil),      // 4: dedupe_engine.BackupResponse
	(*BackupStatus)(nil),        // 5: dedupe_engine.BackupStatus
	(*BackupError)(nil),         // 6: dedupe_engine.BackupError
	(*RestoreRequest)(nil),      // 7: dedupe_engine.RestoreRequest
	(*RestoreResponse)(nil),     // 8: dedupe_engine.RestoreResponse
	(*RestoreDataRequest)(nil),  // 9: dedupe_engine.RestoreDataRequest
	(*RestoreDataResponse)(nil), // 10: dedupe_engine.RestoreDataResponse
}
var file_pkg_api_dedupe_engine_proto_depIdxs = []int32{
	0,  // 0: dedupe_engine.BackupRequest.start_backup:type_name -> dedupe_engine.BackupStart
	1,  // 1: dedupe_engine.BackupRequest.file_segment:type_name -> dedupe_engine.FileSegment
	3,  // 2: dedupe_engine.BackupRequest.end_backup:type_name -> dedupe_engine.BackupEnd
	5,  // 3: dedupe_engine.BackupResponse.status_update:type_name -> dedupe_engine.BackupStatus
	6,  // 4: dedupe_engine.BackupResponse.error_message:type_name -> dedupe_engine.BackupError
	2,  // 5: dedupe_engine.BackupService.StreamBackup:input_type -> dedupe_engine.BackupRequest
	7,  // 6: dedupe_engine.BackupService.InitiateRestore:input_type -> dedupe_engine.RestoreRequest
	9,  // 7: dedupe_engine.BackupService.StreamRestoreData:input_type -> dedupe_engine.RestoreDataRequest
	4,  // 8: dedupe_engine.BackupService.StreamBackup:output_type -> dedupe_engine.BackupResponse
	8,  // 9: dedupe_engine.BackupService.InitiateRestore:output_type -> dedupe_engine.RestoreResponse
	10, // 10: dedupe_engine.BackupService.StreamRestoreData:output_type -> dedupe_engine.RestoreDataResponse
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_api_dedupe_engine_proto_init() }
func file_pkg_api_dedupe_engine_proto_init() {
	if File_pkg_api_dedupe_engine_proto != nil {
		return
	}
	file_pkg_api_dedupe_engine_proto_msgTypes[2].OneofWrappers = []any{
		(*BackupRequest_StartBackup)(nil),
		(*BackupRequest_FileSegment)(nil),
		(*BackupRequest_EndBackup)(nil),
	}
	file_pkg_api_dedupe_engine_proto_msgTypes[4].OneofWrappers = []any{
		(*BackupResponse_StatusUpdate)(nil),
		(*BackupResponse_ErrorMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_dedupe_engine_proto_rawDesc), len(file_pkg_api_dedupe_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_dedupe_engine_proto_goTypes,
		DependencyIndexes: file_pkg_api_dedupe_engine_proto_depIdxs,
		MessageInfos:      file_pkg_api_dedupe_engine_proto_msgTypes,
	}.Build()
	File_pkg_api_dedupe_engine_proto = out.File
	file_pkg_api_dedupe_engine_proto_goTypes = nil
	file_pkg_api_dedupe_engine_proto_depIdxs = nil
}
