apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio-storage
  namespace: dedupe-engine
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  type: pd-ssd 