apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data-0
  namespace: dedupe-engine
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: minio-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data-1
  namespace: dedupe-engine
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: minio-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data-2
  namespace: dedupe-engine
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: minio-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data-3
  namespace: dedupe-engine
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: minio-storage
  resources:
    requests:
      storage: 10Gi 