apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: dedupe-engine
data:
  config.env: |
    # MinIO Server Configuration
    MINIO_ROOT_USER=minioadmin
    MINIO_ROOT_PASSWORD=minioadmin123
    MINIO_SERVER_URL=https://minio.dedupe-engine.svc.cluster.local
    MINIO_BROWSER_REDIRECT_URL=https://minio.dedupe-engine.svc.cluster.local
    
    # Erasure Coding Configuration
    MINIO_ERASURE_CODING_DRIVES=4
    MINIO_ERASURE_CODING_PARITY=2
    
    # Performance Tuning
    MINIO_CACHE_DRIVES=/cache
    MINIO_CACHE_EXCLUDE=*.pdf;*.doc;*.docx
    MINIO_CACHE_EXPIRY=90h
    MINIO_CACHE_MAXUSE=80
    
    # Security
    MINIO_IDENTITY_OPENID_CONFIG_URL=
    MINIO_IDENTITY_OPENID_CLIENT_ID=
    MINIO_IDENTITY_OPENID_CLIENT_SECRET= 